name: cr_form
description: A new Flutter project.
version: 0.0.11
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter

  render_metrics: ^2.0.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
